version: '3.8'
services:
  bot:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
      - ./airdrop.db:/app/airdrop.db
      - ./bot.log:/app/bot.log
      - ./users.xlsx:/app/users.xlsx
    restart: unless-stopped
  redis:
    image: redis:7.0
    restart: unless-stopped
